@startuml
'https://plantuml.com/class-diagram

class JavaFX.Main {
    -start()
    -main()
}

class Checker {
    +duplicates()
    +valueFormat()
    +serialLength()
    +validName()
    +allValues()
}

class JavaFX.Columns {
    +setValueColumn()
    +setSerialColumn()
    +setNameColumn()
}

class JavaFX.EditController {
    -TextField editValueField
    -TextField editSerialField
    -TextField editNameField
    -Observable list

    +clickConfirmEdit()
    +getNewItem()
    +nullNewItem()
    +transferObservableList()
    +transferValue()
    +transferSerial()
    +transferName()
}

class JavaFX.Errors {
    -string
    +displayError()
}

class JavaFX.InventoryController {

	-searchField
	-valueField
	-serialField
	-editNameField

	-tableVIewContainer
	-data
	-dataTemp

	-dueDateColumn
	-todoFieldColumn
	-boolColumn

	-fileChooser
	-ManageFile mf
	-Search sc
	-Checker check

    +initialize()
    +clickAddList()
    +clickNewItem()
    +clickDeleteItem()

    +menuLoadFile()
    +menuSaveFile()
    +menuQuit()

    +clickSearch()
    +clickReset()
    +clickEditItem()

    -showEditWindow()
    -setEditPopupValues()

}

class InventoryItem {

    -String itemValue
    -String itemSerial
    -String itemName

    +getItemValue()
    +getItemSerial()
    +getItemName()

    +setItemValue()
    +setItemSerial()
    +setItemName()

    - valueFormatting()

}

class ManageFile {

    -defaultPath
    -filePath
    -fileName
    -stringOfList

    +setFileName()
    +getFileName()

    +setFilePath()
    +getFilePath()

    +setStringOfList()
    +getStringOfList()

    +writeFile()
    +readFile()
}

class Parser {
    +fromHTML()
    +toHTML()

    +fromTSV()
    +toTSV()

    +stringToList()
}

class Search {
    +findItem()
}


JavaFX.Main ==> JavaFX.InventoryController

JavaFX.InventoryController ==> ManageFile
JavaFX.Columns => JavaFX.InventoryController
JavaFX.InventoryController <=> JavaFX.EditController
JavaFX.Errors ==> JavaFX.InventoryController
JavaFX.Errors ==> JavaFX.EditController
JavaFX.Errors ==> Checker
JavaFX.InventoryController <== InventoryItem
JavaFX.EditController <=> Search
JavaFX.EditController <==> Checker
JavaFX.EditController <==> InventoryItem

InventoryItem <-> ManageFile

Checker <--> ManageFile
Search -> Checker

Parser <-> ManageFile






@enduml